
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "emendatusenigmatica", "immersiveengineering", "thermal", "create", "mekanism", "jaopca", "kubejs", "appliedenergistics2", "pneumaticcraft", "occultism", "tmechworks", "industrialforegoing", "botania", "quark", "pedestals"]

