
[FunctionalStorageConfig]
	#Armory slot amount
	#Range: > 1
	ARMORY_CABINET_SIZE = 4096
	#Linking range radius
	DRAWER_CONTROLLER_LINKING_RANGE = 12
	#Every how many ticks the drawer upgrades will work
	UPGRADE_TICK = 4
	#How many items the pulling upgrade will try to pull
	UPGRADE_PULL_ITEMS = 4
	#How much fluid (in mb) the pulling upgrade will try to pull
	UPGRADE_PULL_FLUID = 500
	#How many items the pushing upgrade will try to pull
	UPGRADE_PUSH_ITEMS = 4
	#How much fluid (in mb) the pushing upgrade will try to pull
	UPGRADE_PUSH_FLUID = 500
	#How many items the collector upgrade will try to pull
	UPGRADE_COLLECTOR_ITEMS = 4

