
[FunctionalStorageClientConfig]
	#Drawer content render range in blocks
	#Range: > 1
	DRAWER_RENDER_RANGE = 16
	#The thickness of 3D item/block displays
	#Range: 0.05 ~ 0.75
	DRAWER_RENDER_THICKNESS = 0.125

