
[General]
	#Totem Maximum Soul Count and Threshold to save the Player, Default: 10000
	#Range: > 10
	maxSouls = 10000
	#Arca Maximum Soul Count, Default: 100000
	#Range: > 10
	maxArcaSouls = 100000
	#Totem of Souls will save the Player if full of Soul Energy and its in Curio Slot, hotbar or off-hand, Default: true
	totemUndying = true
	#Arca will save the Player if past Totem Maximum Soul Count, Default: true
	arcaUndying = true
	#Gives Players a Totem of Roots when first entering World, Default: false
	starterTotem = false
	#Gives Players the Black Book when first entering World and Patchouli is loaded, Default: false
	starterBook = false
	#Gives Players the Witch's Brew when first entering World and Patchouli is loaded, Default: false
	starterWitchBook = false
	#Show the Soul Energy Bar if Player has Totem of Souls/Arca, Default: true
	soulGuiShow = true
	#Show currently equipped focus on Wand/Staff in Gui, Default: true
	focusGuiShow = true
	#Whether Wands and Staffs show cooldown if the focus it's equipped with is, Default: true
	showWandCooldown = true
	#Show numerical amount of Souls on the Soul Energy Bar, Default: false
	showNumber = false
	#Horizontal Position of where the Soul Energy Bar is located, Default: 100
	#Range: > -2147483647
	soulGuiHorizontal = 100
	#Vertical Position of where the Soul Energy Bar is located, Default: -5
	#Range: > -2147483647
	soulGuiVertical = -5
	#Move where the equipped Focus is located horizontally from its original position (- = Left, + = Right), Default: 0
	#Range: > -2147483647
	focusGuiHorizontal = 0
	#Move where the equipped Focus is located vertically from its original position (- = Up, + = Down), Default: 0
	#Range: > -2147483647
	focusGuiVertical = 0
	#Bosses from the Mod has custom looking Boss Bars. Default: true
	specialBossBar = true
	#Bosses from the Mod has custom Music Playing. Default: true
	bossMusic = true
	#Allows player movement if Focus/Brew Wheel are open, Default: true
	wheelGuiMovement = true
	#Players camera can shake. Default: true
	cameraShake = true

[Blocks]
	#Add mobs that Hook Bells don't work on. 
	#To do so, enter the namespace ID of the mob, like "minecraft:zombie, minecraft:skeleton".
	hookBellBlackList = []
	#Whether Night Beacons are allowed to function, turning Daytime to Midnight so long as it's activated, Default: true
	enableNightBeacon = true
	#Maximum level of experience the Dark Anvil will stick to instead of capping if Cap is disabled, Default: 30
	#Range: > 1
	darkAnvilRepairCost = 30
	#Whether Dark Anvils have a cap that prevents items from being repaired or enchanted if repair cost is exceeded, Default: false
	darkAnvilCap = false
	#Whether Dark Anvils will take Experience Points instead of Levels, Default: false
	darkAnvilTakePoints = false
	#Whether Dark Anvils ignores enchantment max levels when combining same enchantments, Default: true
	darkAnvilIgnoreMaxLevels = true
	#How much Soul Energy is required for the Dark Anvil to repair itself, Default: 1000
	#Range: > 0
	darkAnvilSoulCost = 1000
	#The amount of Soul Energy used up to repair Items per the configured amount of seconds, Default: 1
	#Range: > 0
	soulMenderCost = 1
	#How many seconds the Soul Menderer repairs 1 durability from an item, Default: 0.5
	#Range: 0.0 ~ 1.7976931348623157E308
	soulMenderSeconds = 0.5
	#The amount of Soul Energy used to give Charges to the Sculk Grower, Default: 20
	#Range: > 0
	sculkGrowerCost = 20
	#How much Charges is given to the Sculk Grower whenever it absorbs Soul Energy, Default: 100
	#Range: > 0
	sculkGrowerCharge = 100
	#Whether Sculk Grower continues to grow plants without Redstone if it still contains charges. Setting it to false will cause the Sculk Grower to slowly decay its charges, Default: true
	sculkGrowerContinue = true
	#Whether Sculk Grower can accept Potency enchantment, which allows the Grower to grow plants faster, Default: true
	sculkGrowerPotency = true
	#Allow looted Pithos to regenerate Loot and spawn Skull Lord again when right-clicked with respawn_boss tagged item, Default: true
	pithosRespawn = true
	#Allow used Crystal Balls to spawn Crones again when right-clicked with respawn_boss tagged item, Default: true
	crystalBallRespawn = true

["Soul Taken"]
	#Multiplies the amount of Souls taken by this amount, Default: 2
	#Range: > 1
	soulTakenMultiplier = 2
	#Undead Killed, Default: 5
	#Range: > 0
	undeadSouls = 5
	#Anthropods Killed, Default: 5
	#Range: > 0
	anthropodSouls = 5
	#Animals Killed, Default: 5
	#Range: > 0
	animalSouls = 5
	#Illagers, Witches, Cultists Killed, Default: 25
	#Range: > 0
	illagerSouls = 25
	#Villagers Killed, Default: 100
	#Range: > 0
	villagerSouls = 100
	#Non-Undead Piglin Killed, Default: 10
	#Range: > 0
	piglinSouls = 10
	#Ender Dragon Killed, Default: 1000
	#Range: > 0
	enderDragonSouls = 1000
	#Enderman Killed, Default: 10
	#Range: > 0
	endermanSouls = 10
	#Warden Killed, Default: 10000
	#Range: > 0
	wardenSouls = 10000
	#Players Killed, Default: 100
	#Range: > 0
	playerSouls = 100
	#Others Killed, Default: 5
	#Range: > 0
	otherSouls = 5

[Lich]
	#Enable Liches healing using Soul Energy, Default: true
	lichSoulHeal = true
	#How much Soul Energy is cost to heal the Player per configured second if they've become a Lich, Default: 5
	#Range: > 0
	lichHealCost = 5
	#How many seconds until Lich Players heals using Soul Energy, Default: 1
	#Range: > 0
	lichHealSeconds = 1
	#How much health Lich Players heals using Soul Energy, Default: 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	lichHealAmount = 1.0
	#Enable to get infinite Night Vision when being a Lich, Default: true
	lichNightVision = true
	#Wearing Helmet in Sunlight as a Lich periodically damages it, Default: true
	lichDamageHelmet = true
	#Undead Mobs will not attack you if you're a Lich and will even defend you if you're attack by another mob and wearing the Necro Set, Default: true
	lichUndeadFriendly = true
	#Enable to make Liches 85% more resistant to Magic Attacks, Default: false
	lichMagicResist = false
	#If Lich Undead Friendly is set to true, Only undead that have lower than 50 Hearts are friendly, Default: true
	lichPowerfulHostile = true
	#If Villagers provide negative Reputation to Liches and non-Player Iron Golems are automatically aggressive against them, Default: true
	lichVillagerHate = true
	#Whether the player needs to read a Forbidden Scroll to start the Potion of Transformation ritual, Default: true
	lichScrollRequirement = true
	#Whether players can obtain Lichdom without commands, Default: true
	lichEnable = true
	#Enable Liches healing be stunted when hurt by Smite Enchantment, Default: true
	lichSmite = true

