
#Client only settings, mostly things related to rendering
[client]
	#Set to true to enable rendering curios
	renderCurios = true
	#The X-Offset for the Curios GUI button
	#Range: -100 ~ 100
	buttonXOffset = 0
	#The Y-Offset for the Curios GUI button
	#Range: -100 ~ 100
	buttonYOffset = 0
	#The X-Offset for the Creative Curios GUI button
	#Range: -100 ~ 100
	creativeButtonXOffset = 0
	#The Y-Offset for the Creative Curios GUI button
	#Range: -100 ~ 100
	creativeButtonYOffset = 0
	#The corner for the Curios GUI button
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	buttonCorner = "TOP_LEFT"
	#Set to true to enable the Curios GUI button
	enableButton = true

