
["Cursery settings"]
	#Should enchanted books show a hint for curse magic, default:true
	showDesc = true
	#Add a curse id here to exclude it from beeing applied. To put multiple values seperate them by commas like this:  ["minecraft:curse", "mod:curse;"] 
	excludedCUrses = ["minecraft:vanishing_curse"]
	#Should applying treasure enchants be excluded, default:false
	excludeTreasure = false
	#Base curse application chance, scales up the more enchants the item has. Default:5 %
	#Range: 1 ~ 100
	basecursechance = 5
	#Whether to log debug messages about curse rng beeing rolled, default = false
	debugTries = false
	#List of items to disable, they get replaced by air e.g. ["minecraft:elytra"]
	disabledItems = []
	#Should enchanting success play a sound and show particles, default:true
	visualSuccess = true

