
#DoesPotatoTick?
["Living Entities Tick Settings"]
	#If you disable this, entities will not stop ticking when they'are far from you, this mod may be useless for you too
	OptimizeEntitiesTicking = true
	#Range: > 1
	LivingEntitiesMaxHorizontalTickDistance = 64
	#Range: > 1
	LivingEntitiesMaxVerticalTickDistance = 32
	#If you don't want an entity to be affected by the optimization, you can write its registry name down here.
	EntitiesWhitelist = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:wither", "minecraft:player", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "alexsmobs:spectre", "twilightforest:naga", "twilightforest:lich", "twilightforest:yeti", "twilightforest:snow_queen", "twilightforest:minoshroom", "twilightforest:hydra", "twilightforest:knight_phantom", "twilightforest:ur_ghast", "atum:pharaoh", "mowziesmobs:barako", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "mowziesmobs:naga", "aoa3:skeletron", "aoa3:smash", "aoa3:baroness", "aoa3:clunkhead", "aoa3:corallus", "aoa3:cotton_candor", "aoa3:craexxeus", "aoa3:xxeus", "aoa3:creep", "aoa3:crystocore", "aoa3:dracyon", "aoa3:graw", "aoa3:gyro", "aoa3:hive_king", "aoa3:kajaros", "aoa3:miskel", "aoa3:harkos", "aoa3:raxxan", "aoa3:okazor", "aoa3:king_bambambam", "aoa3:king_shroomus", "aoa3:kror", "aoa3:mechbot", "aoa3:nethengeic_wither", "aoa3:red_guardian", "aoa3:blue_guardian", "aoa3:green_guardian", "aoa3:yellow_guardian", "aoa3:rock_rider", "aoa3:shadowlord", "aoa3:tyrosaur", "aoa3:vinecorne", "aoa3:visualent", "aoa3:voxxulon", "aoa3:bane", "aoa3:elusive", "gaiadimension:malachite_drone", "gaiadimension:malachite_guard", "blue_skies:alchemist", "blue_skies:arachnarch", "blue_skies:starlit_crusher", "blue_skies:summoner", "stalwart_dungeons:awful_ghast", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:shelterer_without_armor", "dungeonsmod:extrapart", "dungeonsmod:king", "dungeonsmod:deserted", "dungeonsmod:crawler", "dungeonsmod:ironslime", "dungeonsmod:kraken", "dungeonsmod:voidmaster", "dungeonsmod:lordskeleton", "dungeonsmod:winterhunter", "dungeonsmod:sun", "forestcraft:beequeen", "forestcraft:iguana_king", "forestcraft:cosmic_fiend", "forestcraft:nether_scourge", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:ignis", "cataclysm:ignited_revenant", "cataclysm:netherite_monstrosity", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:dragon_multipart"]
	#If you don't want entities of a mod to be affected by the optimization, you can write its modid down here
	EntitiesModIDWhiteList = ["create", "witherstormmod"]
	#With this turned on, all the raider won't stop ticking in raid chunks even if they are far from players (well this is not perfect as the raiders may walk out of the raid range)
	TickRaidersInRaid = true
	#Similar with entity whitelist, but only take effect in raid.
	RaidEntitiesWhiteList = ["minecraft:witch", "minecraft:vex"]
	#Similar with entity modID whitelist, but only take effect in raid
	RaidEntitiesModIDWhiteList = []
	#Leave this empty for applying to all the dimensions
	#Entities in these dimensions will be affected by the optimization
	DimensionWhitelist = []
	#This this is enabled, tickable check will run a lot faster, but the entity will not die out of range
	IgnoreDeadEntities = false

["Item Entities Tick Settings"]
	#Slow down item entities' ticking speed by 1/4
	OptimizeItemMovement = false
	#If you don't want to let a specific item entity in the world to be effected by the optimization, you can write its registry name down here.
	#Require 'OptimizeItemMovement' to be true
	ItemWhiteList = ["minecraft:cobblestone"]

[Misc]
	SendWarningMessageWhenPlayerLogIn = true

