
#Dynamic Lights Settings
[Settings]

	[Settings."Lighting Settings"]
		"Dynamic TileEntity Lighting" = true
		"Only Update On Position Change" = true
		#Allowed Values: OFF, SLOW, FAST, REALTIME
		"Quality Mode (OFF, SLOW, FAST, REALTIME)" = "FAST"
		"Dynamic Entity Lighting" = true

