
[embeddiumplus]

	[embeddiumplus.general]
		#Configure FPS Display mode
		#Complete mode gives you min FPS count and average count
		#Allowed Values: OFF, SIMPLE, ADVANCED
		fpsDisplay = "ADVANCED"
		#Shows GPU and memory usage onto FPS display
		#Allowed Values: OFF, ON, GPU, RAM
		fpsDisplaySystem = "OFF"
		#Set Fullscreen mode
		#Borderless let you change between screens more faster and move your mouse across monitors
		#Allowed Values: WINDOWED, BORDERLESS, FULLSCREEN
		fullscreen = "WINDOWED"
		#Configure FPS Display gravity
		#Places counter on specified corner of your screen
		#Allowed Values: LEFT, CENTER, RIGHT
		fpsDisplayGravity = "LEFT"
		#Toggle FPS Display shadow
		#In case sometimes you can't see the text
		fpsDisplayShadow = false
		#Configure FPS Display margin
		#Give some space between corner and text
		#Range: 0 ~ 48
		fpsDisplayMargin = 12

	[embeddiumplus.performance]
		#Toggles JREI item rendering until searching
		#Increases performance a little bit and cleans your screen when you don't want to use it
		hideJREI = false
		#Toggles FastChest feature
		#Without flywheel installed or using any backend, it increases FPS significatly on chest rooms
		fastChests = false
		#Toggles FastBeds feature
		fastBeds = true
		#Toggles Minecraft Fonts shadows
		#Depending of the case may increase performance
		#Gives a flat style text
		fontShadows = true

		[embeddiumplus.performance.distanceCulling]

			[embeddiumplus.performance.distanceCulling.entities]
				#Configure horizontal max distance before cull entities
				#Value is squared, default was 64^2 (or 64x64)
				#Range: > 0
				cullingMaxDistanceX = 4096
				#Toggles distance culling for entities
				#Maybe you use another mod for that :(
				enable = true
				#Configure vertical max distance before cull entities
				#Value is raw
				#Range: 0 ~ 512
				cullingMaxDistanceY = 32
				#List of all Entities to be ignored by distance culling
				#Uses ResourceLocation to identify it
				#Example 1: "minecraft:bat" - Ignores bats only
				#Example 2: "alexsmobs:*" - ignores all entities for alexmobs mod
				whitelist = ["minecraft:ghast", "minecraft:ender_dragon", "iceandfire:*", "create:*"]

			[embeddiumplus.performance.distanceCulling.tileEntities]
				#Configure horizontal max distance before cull Block entities
				#Value is squared, default was 64^2 (or 64x64)
				#Range: > 0
				cullingMaxDistanceX = 4096
				#Toggles distance culling for Block Entities
				#Maybe you use another mod for that :(
				enable = true
				#Configure vertical max distance before cull Block entities
				#Value is raw
				#Range: 0 ~ 512
				cullingMaxDistanceY = 32
				#List of all Block Entities to be ignored by distance culling
				#Uses ResourceLocation to identify it
				#Example 1: "minecraft:chest" - Ignores chests only
				#Example 2: "ae2:*" - ignores all Block entities from Applied Energetics 2
				whitelist = ["waterframes:*"]

	[embeddiumplus.dynlights]
		#Toggle if Block Entities should have dynamic lights
		onTileEntities = true
		#Configure how fast light whould be updated
		#Allowed Values: OFF, SLOW, NORMAL, FAST, SUPERFAST, FASTESTS, REALTIME
		updateSpeed = "REALTIME"
		#Toggle if Entities should have dynamic lights
		onEntities = true
		updateOnlyOnPositionChange = true

	[embeddiumplus.others]
		#Configure if borderless fullscreen option should be attached to F11 or replace vanilla fullscreen
		#Allowed Values: ATTACH, REPLACE, OFF
		borderlessAttachModeOnF11 = "ATTACH"
		#Toggles fast language reload
		#Embeddedt points it maybe cause troubles to JEI, so Â¿why not add it as a toggleable option?
		fastLanguageReload = false

	[embeddiumplus.quality]
		#Chunks fade in speed
		#This option doesn't affect performance, just changes speed
		#Allowed Values: OFF, FAST, SLOW
		chunkFadeSpeed = "SLOW"
		#Raise clouds
		#Modify clouds height perfect for a adaptative world experience
		#Range: 0 ~ 512
		cloudsHeight = 192
		#Toggle fog feature
		#Fog was a vanilla feature, toggling off may increases performance
		fog = true

		[embeddiumplus.quality.darkness]
			#Configure fog brightness on nether when darkness is enabled
			#Range: 0.0 ~ 1.0
			endFogBright = 0.5
			#Configure min moon brightness level with darkness
			#Range: 0.0 ~ 1.0
			newMoonBright = 0.0
			#Toggle Darkness on End dimension
			enableOnEnd = false
			#Toggle Darkness default mode for modded dimensions
			valueByDefault = false
			#Configure Darkness Mode
			#Each config changes what is considered 'true darkness'
			#Allowed Values: TOTAL_DARKNESS, PITCH_BLACK, DARK, DIM, OFF
			mode = "OFF"
			#Toggles if moon phases affects darkness in the overworld
			affectedByMoonPhase = true
			#List of all dimensions to use True Darkness
			#This option overrides 'valueByDefault' state
			dimensionWhitelist = []
			#Configure max moon brightness level with darkness
			#Range: 0.0 ~ 1.0
			fullMoonBright = 0.25
			#Configure fog brightness on nether when darkness is enabled
			#Range: 0.0 ~ 1.0
			netherFogBright = 0.5
			#Toggle Darkness on Nether dimension
			enableOnNether = false
			#Toggle darkness when dimension has no SkyLight
			enableOnNoSkyLight = false
			#Disables all bright sources of darkness like moon or fog
			#Only affects darkness effect
			enableBlockLightOnly = false
			#Toggle Darkness on Overworld dimension
			enableOnOverworld = true

