
#Recipe book
[recipe_book]
	#Should the Oven have a Recipe Book available on its interface?
	enableRecipeBookOven = false

#Mint
[mint_spread]
	#Should mint spread?
	shouldMintSpread = false
	#How fast should mint spread? (Higher number = Slower)
	#Range: 1 ~ 100
	mintSpreadRate = 100

