# Enable forge global version checking
versionCheck = true
# does the splashscreen run
splashscreen = true
# Disables Optimized DFU client-side.
disableOptimizedDFU = true
defaultConfigPath = "defaultconfigs"
# max threads for parallel loading : -1 uses Runtime#availableProcessors
maxThreads = -1

