
[friendly-fire]
	#Whether or not you can take friendly fire from players in your party.
	"Friendly Fire Disabled" = true

	[friendly-fire.server-options]
		#Whether or not to allow players to teleport to eachother within a party
		"Allow teleportation" = true
		#Whether or not to auto-assign all players to a party
		"Auto-assign Parties" = false
		#Whether or not to allow invite all
		"Allow Invite All" = false
		#Whether or not debug mode is enabled
		"Enable Debug Mode" = false

