
[toughness]
	#Render a separate armor bar for the armor toughness attribute (from diamond and netherite armor).
	#Having only this option active will make the toughness bar behave just like vanilla's armor bar without any colorful stacking or so.
	armor_toughness_bar = true
	#Render row count to indicate total amount of rows since not all may be visible at once due to the stacked rendering.
	allow_count = true
	#Show colorful icons on the front row, not just on all subsequent rows.
	colorize_first_row = false
	#Shift toughness bar up or down by specified number of icon rows. Allows for better mod compat on Fabric, has no effect on Forge.
	#Range: -5 ~ 5
	toughness_bar_row_shift = 0
	#Render the toughness bar on the left side above the hotbar (where health and armor is rendered).
	left_side = false
	#Add layers to this bar. When disabled any modifications to the bar from this mod will be turned off.
	allow_layers = true
	#Don't draw empty armor points, this will make the armor bar potentially shorter.
	skip_empty_armor_points = true
	#Use vanilla's icons on all front rows, use custom colored icons on the background row.
	inverse_coloring = false

[health]
	#Show colorful icons on the front row, not just on all subsequent rows.
	colorize_first_row = true
	#Add layers to this bar. When disabled any modifications to the bar from this mod will be turned off.
	allow_layers = true
	#Render row count to indicate total amount of rows since not all may be visible at once due to the stacked rendering.
	allow_count = true
	#Use vanilla's icons on all front rows, use custom colored icons on the background row.
	inverse_coloring = false

[armor]
	#Show colorful icons on the front row, not just on all subsequent rows.
	colorize_first_row = true
	#Add layers to this bar. When disabled any modifications to the bar from this mod will be turned off.
	allow_layers = true
	#Don't draw empty armor points, this will make the armor bar potentially shorter.
	skip_empty_armor_points = true
	#Render row count to indicate total amount of rows since not all may be visible at once due to the stacked rendering.
	allow_count = true
	#Use vanilla's icons on all front rows, use custom colored icons on the background row.
	inverse_coloring = false

[row_count]
	#Color of row count, use any chat formatting color value.
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
	row_count_color = "WHITE"
	#Only include completely filled rows for the row count.
	count_full_rows_only = false
	#Force drawing row count using the font renderer, will make numbers display larger.
	force_font_renderer = false
	#Show row count also when only one row is present.
	always_render_row_count = false
	#Render an 'x' together with the row count number.
	row_count_x = true

[general]
	#Move chat messages above armor/absorption bar.
	move_chat_above_armor = true

[integration]
	#Disables restored health preview in Apple Skin mod as it conflicts with stacked heart rendering. Only disable when integration breaks.
	apple_skin_integration = true

