
[General]
	#Allowed Values: DISPLAY_ALL, DISPLAY_MY, DISPLAY_OTHERS, HIDE
	"Pet Mode" = "DISPLAY_ALL"

[Tooltips]
	#Display food properties in tooltips
	"Food Icons" = true
	#Display equipment attributes in tooltips
	"Equipment Icons" = true

